language: node_js
node_js:
- '8'
branches:
- only:
  - master
before_script:
- npm install -g firebase-tools
script: 
- npm run build && npm run test
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: e/cLc1QXWTzgHtnrYpkq4qSDSVK8E4GutYhu9jtIIkfZtc5oEecOeGfsoVBbyoD5jdf7oUdlbwZk3BaImwaKOBaKzqmKSGVCG4wD2tS7M7n705LP3UY1Xx9n6P33dUtJQkyv6nKWnj/aldSEAE7KLdGhYcHPX/O2bz/52MxV4ZZkEEiI1+z9+S8mToaXHVUaU51YoeTP9XS4h/Zqh1Kpd3/uRmMzfo6llc+SjPakGco3PF7357HlDKoe2kEWjcIC4wljkm5udAIEUmhUDWyQjmOWRcQzDDPT6o8DtUnbLEOQDCloeKfjOMimwm2V7/bXmLjtpJeJHTRjBLJbTt/BZhKTivNatsZ7xl6qwP2l7n0LOGulYeo77ibokGklTII81iXfZ8X66KNGar/wBh4E/S7RsyO3SfKvxH2NfIz5ErAYwCf8Nbc99ReUeYX6GE0CT/PKRW4+jYaA01P9DgDwIgcSNN+bnSCu11H9Ya6yfMsTINzhhncG1h8H3oCbJpHIYtY3/yQAjmWQEUvfcgTwRQQQA+ToMaEV57DbkkimaWHM4Pykpl/qyybrDjbvpLSuiCys2x0D8HxDFratEI77qcrqNmJttemWgLIt7F+GpQy/yRyx9eI4HRRpSVZ1SEY74TOQ27UTh5Kwg0ZdJ3E2y2dM+qZ3BJhC+heWI2w3zmc=
  on:
    branch: master
