language: node_js
node_js:
- '8'
branches:
- only:
  - master
install: .travis/install.sh
script: .travis/build.sh
deploy:
  script: bash .travis/deploy.sh
  provider: script
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: AkaxLVM60LN7VVlX5oUB7GfV70obhz42HoAVAD7Yj3POrR84NSRx7l+hIaxgq2NnJVdP37s2TvOICUaiE6LtaOfrSf0y/oOpj3uehehuXUcQ+Jlqueqs/Xd2EDrviRQ+DXEpTVlzDa77pAT1iW5Nfc8Et4Jmw/PCC/bJfVNSzGszWufIHx9IJuSoKjPAttqsdyWbgjozkkwmzBiq0oJRR2WBdWtxqpfI37TdMyn2r10FmSq+Js0cRKI+0WxhzzF4TKIdkF7TfBenIIyB4XfFEKanXiROWIWOBfPDJkcxMvcr2NO+o7p/Yjrcxsku/lcG9qk3Zfoh+UGHSTdvVYbAWkfo6Oel1QqdaKIZfq3G9HZx3ycqEiLznaEy/2bOhbaqWHL5qfBnb2y9lJh825DEopF4re3bOysmI/4zOh4cEuZib5tGcSD9ohCbgTk17YrFzCpLg7NpTUUHhuo3ETpxk8pYbeQ7gJGShJGcuwOlOceDe2kBBi6M2PeqwOipEkrLlrCRPmQzSWCY7UHtbKinu3F8T7rdC8QQM5Z2R6jS8p1D9LiSjjBUvuG2B24p65FjcMFAdt1aX1PePeabA3dyRdVqY4CucYudlpQtrxEH3wIKQXpa5DQa2ggZWCxd2Q5Z1u8GB6jsutuj8Zu5S7I4wCBIpzNm1m8H0T3gfF3g4eo=
