language: node_js
node_js:
- '8'
install: true
script: './build.sh'
branches:
- only:
  - master
env:
  global:
    secure: gCzKBskwe91s8k9r78MtQ4NsUSDWQ2A/SW9LV93qqqAnwan0EXKpplP6vlQZvn8GVZ/5Ez0Ci984rL9Txs+IP/Gt+iQof5YqwRfFDWdAPKONB83PfgL1/17v4Tb1vlKsU+tgPbl8I5qpAmx4GnGFUhC+5VtGuHfqEXILbu1uZhFbOAPjMC1AbSysETfxVZz4OuJA4arkHLiqf3dyUU+tqo4+asG5vxQ2r65AVm0RCqbDBzrktXpZk1Ox1f2vIxXf2wwUGaRpcf7pZC7hS2NiguaF65ByudmqbRAGpkENYdhHsZaohaBAT6FuHHHsddCxuV0tNU97A2zKtnBJbDwyCUPYpgqa+WZ+iRqZGYNBj5JKGo8uya1llwoVDYP8So6aTgk4MKMvx9wCjRYQc27eJsTKiYb4Xg44h1PJTlgGxYVk9tlvWLqCRsp0W1qsYhbiJ/NiQ66A/pbCk/i58LEBA9ycTEbiBUZ8Mmw5A25XmHp8llynJUcJgw+8W0N8W9y3fGWftSWsVL5Gfn/d4EsmG2GKPuZkIckKssHgd3XfK/S6zl6ZWuELrW+zsgvrYMJSWrLZ11pGYvqCDe01Bd5RFdiLrPDVZnwoWfL74lqYldaoV1IidIacNwX4mHxEFToXznpoRPyj5zIr/i42bQwqTdt8t+wSjACpjz+CXmRaoH4=
