/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';

import {
  MatchResults,
} from '@stencil/router';

import {
  InstanceList as InstanceList
} from './components/instance-list/instance-list';

declare global {
  interface HTMLInstanceListElement extends InstanceList, HTMLStencilElement {
  }
  var HTMLInstanceListElement: {
    prototype: HTMLInstanceListElement;
    new (): HTMLInstanceListElement;
  };
  interface HTMLElementTagNameMap {
    "instance-list": HTMLInstanceListElement;
  }
  interface ElementTagNameMap {
    "instance-list": HTMLInstanceListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "instance-list": JSXElements.InstanceListAttributes;
    }
  }
  namespace JSXElements {
    export interface InstanceListAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  InstancePage as InstancePage
} from './components/instance-page/instance-page';

declare global {
  interface HTMLInstancePageElement extends InstancePage, HTMLStencilElement {
  }
  var HTMLInstancePageElement: {
    prototype: HTMLInstancePageElement;
    new (): HTMLInstancePageElement;
  };
  interface HTMLElementTagNameMap {
    "instance-page": HTMLInstancePageElement;
  }
  interface ElementTagNameMap {
    "instance-page": HTMLInstancePageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "instance-page": JSXElements.InstancePageAttributes;
    }
  }
  namespace JSXElements {
    export interface InstancePageAttributes extends HTMLAttributes {
      match?: MatchResults;
    }
  }
}


import {
  MainPage as MainPage
} from './components/main-page/main-page';

declare global {
  interface HTMLMainPageElement extends MainPage, HTMLStencilElement {
  }
  var HTMLMainPageElement: {
    prototype: HTMLMainPageElement;
    new (): HTMLMainPageElement;
  };
  interface HTMLElementTagNameMap {
    "main-page": HTMLMainPageElement;
  }
  interface ElementTagNameMap {
    "main-page": HTMLMainPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "main-page": JSXElements.MainPageAttributes;
    }
  }
  namespace JSXElements {
    export interface MainPageAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
