/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}

import {
  Instance,
} from './global/models';

import {
  InstanceList as InstanceList
} from './components/instance-list/instance-list';

declare global {
  interface HTMLInstanceListElement extends InstanceList, HTMLStencilElement {
  }
  var HTMLInstanceListElement: {
    prototype: HTMLInstanceListElement;
    new (): HTMLInstanceListElement;
  };
  interface HTMLElementTagNameMap {
    "instance-list": HTMLInstanceListElement;
  }
  interface ElementTagNameMap {
    "instance-list": HTMLInstanceListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "instance-list": JSXElements.InstanceListAttributes;
    }
  }
  namespace JSXElements {
    export interface InstanceListAttributes extends HTMLAttributes {
      instances?: Instance[];
    }
  }
}


import {
  LotroCompletionist as LotroCompletionist
} from './components/lotro-completionist/lotro-completionist';

declare global {
  interface HTMLLotroCompletionistElement extends LotroCompletionist, HTMLStencilElement {
  }
  var HTMLLotroCompletionistElement: {
    prototype: HTMLLotroCompletionistElement;
    new (): HTMLLotroCompletionistElement;
  };
  interface HTMLElementTagNameMap {
    "lotro-completionist": HTMLLotroCompletionistElement;
  }
  interface ElementTagNameMap {
    "lotro-completionist": HTMLLotroCompletionistElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "lotro-completionist": JSXElements.LotroCompletionistAttributes;
    }
  }
  namespace JSXElements {
    export interface LotroCompletionistAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  NavHeader as NavHeader
} from './components/nav-header/nav-header';

declare global {
  interface HTMLNavHeaderElement extends NavHeader, HTMLStencilElement {
  }
  var HTMLNavHeaderElement: {
    prototype: HTMLNavHeaderElement;
    new (): HTMLNavHeaderElement;
  };
  interface HTMLElementTagNameMap {
    "nav-header": HTMLNavHeaderElement;
  }
  interface ElementTagNameMap {
    "nav-header": HTMLNavHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "nav-header": JSXElements.NavHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface NavHeaderAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  RaidList as RaidList
} from './components/raid-list/raid-list';

declare global {
  interface HTMLRaidListElement extends RaidList, HTMLStencilElement {
  }
  var HTMLRaidListElement: {
    prototype: HTMLRaidListElement;
    new (): HTMLRaidListElement;
  };
  interface HTMLElementTagNameMap {
    "raid-list": HTMLRaidListElement;
  }
  interface ElementTagNameMap {
    "raid-list": HTMLRaidListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "raid-list": JSXElements.RaidListAttributes;
    }
  }
  namespace JSXElements {
    export interface RaidListAttributes extends HTMLAttributes {
      instances?: Instance[];
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
